name: "Main"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: ./
        id: diawi
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: ./example.apk
      - name: echo output
        run: echo "check here:\n ${{ steps.diawi.outputs['url'] }}"
